//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExam
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ExamPaperID { get; set; }
        public Nullable<System.DateTime> ExpectedStartDate { get; set; }
        public bool isAttempted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime SubmittedDate { get; set; }
    
        public virtual ExamPaper ExamPaper { get; set; }
    }
}
